### ISSUE TITLE
Doesn't work at VS Code v0.9.1.

### ISSUE THREAD

**Issue by Nebu1eto** [Nebu1eto/vscode-fuse#6]
It doesn't works at new version.
I have to see about that. Sorry.

**Comment by Realignist** [comment]
In Visual Studio Code v0.9.1, it supports user-created syntax plugin from tmLanguage file. And it's structure is different with the previous version. So I re-created new plugin by using generator-code and Fuse's tmLanguage files from [here](https://github.com/fusetools/Fuse.SublimePlugin).
